addons: # APT, etc.
  hosts:
    - ci.vm
    - wp.ci.vm
  apt:
    packages:
      - zip
      - unzip
      - gettext
      - postfix
      - libpspell-dev
  mariadb: '10.1'

services: # Services to start-up.
  - mysql
  - postfix
  - memcached
  - redis-server

cache: # Persistent cache directories.
  apt: true
  directories:
    - ~/ws/.persistent
    - ~/.composer/cache

notifications: # Common webhook only.
  email: false
  webhooks:
    urls:
      - https://www.websharks-inc.com/travis/webhook.php
    on_start: always
    on_success: always
    on_failure: always

language: php # A PHP project (always).
script: ./.travis.bash # Bootstrap/runner.

matrix: # Build matrix rows (default configuration).
  include: # Override these in each project.
    - php: '7.0' # WP standard (latest).
      env: CI_RUN=WP=standard,WP_VERSION=latest
    - php: '7.0' # WP multisite (latest).
      env: CI_RUN=WP=multisite,WP_VERSION=latest
    - php: '7.0' # WP standard (nightly).
      env: CI_RUN=WP=standard,WP_VERSION=nightly
    - php: '7.0' # WP multisite (nightly).
      env: CI_RUN=WP=multisite,WP_VERSION=nightly
  allow_failures: # Allow nightly failures.
    - env: CI_RUN=WP=standard,WP_VERSION=nightly
    - env: CI_RUN=WP=multisite,WP_VERSION=nightly
  fast_finish: true # Before allowed failures.

env: # Define these last to allow for appends.
  global: # Global to all matrix rows.
    - CI_CFG_MYSQL_DB_HOST=127.0.0.1
    - CI_CFG_MYSQL_DB_PORT=3306
    - CI_CFG_MYSQL_DB_CHARSET=utf8mb4
    - CI_CFG_MYSQL_DB_COLLATE=utf8mb4_unicode_ci
    - CI_CFG_MYSQL_DB_USERNAME=client
    - CI_CFG_MYSQL_DB_PASSWORD=WzyNh5xXhsjNXwQ
    - CI_CFG_MYSQL_DB_NAME=db0

    - CI_CFG_BUILD_HOST=ci.vm
    - CI_CFG_BUILD_PORT=8080
    - CI_CFG_BUILD_URL=http://ci.vm:8080
    - CI_CFG_BUILD_DIR="${TRAVIS_BUILD_DIR}"
    - CI_CFG_BUILD_DIR_BASENAME="${CI_CFG_BUILD_DIR##*/}"

    - CI_CFG_WP_HOST=wp.ci.vm
    - CI_CFG_WP_PORT=8081
    - CI_CFG_WP_URL=http://wp.ci.vm:8081
    - CI_CFG_WP_DIR=~/ws/apps/wp
    - CI_CFG_WP_DB_PREFIX=wp_
    - CI_CFG_WP_ADMIN=admin

    - CI_CFG_REDIS_HOST=127.0.0.1
    - CI_CFG_REDIS_PORT=6379

    - CI_CFG_MEMCACHE_HOST=127.0.0.1
    - CI_CFG_MEMCACHE_PORT=11211

    - CI_CFG_EMAIL_SMTP_HOST=127.0.0.1
    - CI_CFG_EMAIL_SMTP_PORT=25
    - CI_CFG_EMAIL_SMTP_SECURE=
    - CI_CFG_EMAIL_SMTP_USERNAME=
    - CI_CFG_EMAIL_SMTP_PASSWORD=

    - CI_CFG_LOGS_DIR=~/ws/logs
    - CI_CFG_CACHE_DIR=~/ws/cache

    - CI_CFG_SALT=Atb9vPW5jnxnTSDmBDbKWwbT2cgLCcXsP42mcU9TUEz7qQu6E6gbv7q8HeeJXjG5

# Custom code reinserted here via [custom] marker. Add your <custom></custom> comment markers here please.
